CREATE TABLE IF NOT EXISTS user_roles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(30) NOT NULL UNIQUE,
  name varchar(120) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO user_roles (code, name)
VALUES
  ('FABRICA', 'Fabrica de Contenido'),
  ('LMS', 'LMS'),
  ('ADMIN', 'Administrador')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, is_active = true;

CREATE TABLE IF NOT EXISTS academic_levels (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(40) NOT NULL UNIQUE,
  name varchar(120) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO academic_levels (code, name)
VALUES
  ('PREGRADO', 'Pregrado'),
  ('POSGRADO', 'Posgrado'),
  ('ESPECIALIZACION', 'Especializacion'),
  ('DIPLOMADO', 'Diplomado')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, is_active = true;

CREATE TABLE IF NOT EXISTS subject_statuses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(60) NOT NULL UNIQUE,
  name varchar(160) NOT NULL,
  sort_order integer NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO subject_statuses (code, name, sort_order)
VALUES
  ('pendiente', 'PENDIENTE', 10),
  ('aprobado', 'APROBADO', 20),
  ('requiere_ajustes', 'REQUIERE AJUSTES', 30)
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order,
    is_active = true;

CREATE TABLE IF NOT EXISTS semesters (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(40) NOT NULL UNIQUE,
  name varchar(120) NOT NULL,
  sort_order integer NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO semesters (code, name, sort_order)
VALUES
  ('2026-1', '2026-1', 202601),
  ('2026-2', '2026-2', 202602),
  ('2027-1', '2027-1', 202701),
  ('2027-2', '2027-2', 202702),
  ('2028-1', '2028-1', 202801),
  ('2028-2', '2028-2', 202802),
  ('2029-1', '2029-1', 202901),
  ('2029-2', '2029-2', 202902),
  ('2030-1', '2030-1', 203001),
  ('2030-2', '2030-2', 203002),
  ('2031-1', '2031-1', 203101),
  ('2031-2', '2031-2', 203102),
  ('2032-1', '2032-1', 203201),
  ('2032-2', '2032-2', 203202),
  ('2033-1', '2033-1', 203301),
  ('2033-2', '2033-2', 203302),
  ('2034-1', '2034-1', 203401),
  ('2034-2', '2034-2', 203402),
  ('2035-1', '2035-1', 203501),
  ('2035-2', '2035-2', 203502)
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order,
    is_active = true;

CREATE TABLE IF NOT EXISTS programs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(80) NOT NULL UNIQUE,
  name varchar(180) NOT NULL UNIQUE,
  sort_order integer NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO programs (code, name, sort_order)
VALUES
  ('ADMINISTRACION_EMPRESAS', 'Administración de Empresas', 10),
  ('INGENIERIA_SISTEMAS', 'Ingeniería de Sistemas', 20),
  ('DISENO_GRAFICO', 'Diseño Gráfico', 30)
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order,
    is_active = true;

CREATE TABLE IF NOT EXISTS content_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(60) NOT NULL UNIQUE,
  name varchar(120) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO content_types (code, name)
VALUES
  ('VIDEO', 'Video'),
  ('PDF', 'PDF'),
  ('PODCAST', 'Podcast'),
  ('PRESENTACION', 'Presentacion'),
  ('ACTIVIDAD_INTERACTIVA', 'Actividad interactiva'),
  ('EVALUACION', 'Evaluacion'),
  ('SCORM', 'SCORM'),
  ('OTRO', 'Otro')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, is_active = true;

CREATE TABLE IF NOT EXISTS comment_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(40) NOT NULL UNIQUE,
  name varchar(120) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO comment_types (code, name)
VALUES
  ('GENERAL', 'General'),
  ('DEVOLUCION', 'Devolucion'),
  ('ERROR', 'Error'),
  ('CIERRE', 'Cierre')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, is_active = true;

CREATE TABLE IF NOT EXISTS notification_statuses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(40) NOT NULL UNIQUE,
  name varchar(120) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO notification_statuses (code, name)
VALUES
  ('PENDING', 'Pendiente'),
  ('SENT', 'Enviada'),
  ('FAILED', 'Fallida'),
  ('SKIPPED', 'Omitida')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, is_active = true;

CREATE TABLE IF NOT EXISTS notification_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(60) NOT NULL UNIQUE,
  name varchar(160) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO notification_types (code, name)
VALUES
  ('SUBJECT_CREATED', 'Materia creada'),
  ('SUBJECT_RETURNED', 'Materia devuelta'),
  ('SUBJECT_COMPLETED', 'Materia completada'),
  ('SUBJECT_CORRECTIONS_READY', 'Correcciones listas'),
  ('SUBJECT_ERROR', 'Error en materia'),
  ('SUBJECT_STATUS_UPDATED', 'Estado actualizado')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, is_active = true;

CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  google_sub varchar(255) NOT NULL UNIQUE,
  email varchar(255) NOT NULL UNIQUE,
  full_name varchar(160) NOT NULL,
  role varchar(30) NOT NULL DEFAULT 'FABRICA' REFERENCES user_roles(code),
  area varchar(120),
  avatar_url text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS materias (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(220) NOT NULL,
  semester varchar(40) NOT NULL REFERENCES semesters(code),
  academic_level varchar(40) NOT NULL REFERENCES academic_levels(code),
  program_name varchar(180) NOT NULL REFERENCES programs(name) ON UPDATE CASCADE,
  content_description text NOT NULL,
  drive_folder_url text NOT NULL,
  cdigital_url text,
  current_status varchar(60) NOT NULL DEFAULT 'pendiente' REFERENCES subject_statuses(code),
  created_by_user_id integer NOT NULL REFERENCES users(id),
  assigned_lms_user_id integer REFERENCES users(id),
  reviewed_at timestamptz,
  completed_at timestamptz,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_materias_status ON materias(current_status);
CREATE INDEX IF NOT EXISTS idx_materias_creator ON materias(created_by_user_id);
CREATE INDEX IF NOT EXISTS idx_materias_program ON materias(program_name);
CREATE INDEX IF NOT EXISTS idx_materias_created_at ON materias(created_at);

CREATE TABLE IF NOT EXISTS subject_transfer_files (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id integer NOT NULL REFERENCES materias(id) ON DELETE CASCADE,
  file_name text NOT NULL,
  file_path text[] NOT NULL DEFAULT '{}',
  mega_url text NOT NULL,
  size_bytes bigint,
  mime_type text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_subject_transfer_files_subject ON subject_transfer_files(subject_id);

CREATE TABLE IF NOT EXISTS subject_content_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id integer NOT NULL REFERENCES materias(id) ON DELETE CASCADE,
  content_type_id integer NOT NULL REFERENCES content_types(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (subject_id, content_type_id)
);

CREATE TABLE IF NOT EXISTS status_history (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id integer NOT NULL REFERENCES materias(id) ON DELETE CASCADE,
  previous_status varchar(60) REFERENCES subject_statuses(code),
  new_status varchar(60) NOT NULL REFERENCES subject_statuses(code),
  changed_by_user_id integer NOT NULL REFERENCES users(id),
  observation text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_status_history_subject ON status_history(subject_id);

CREATE TABLE IF NOT EXISTS comments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id integer NOT NULL REFERENCES materias(id) ON DELETE CASCADE,
  author_user_id integer NOT NULL REFERENCES users(id),
  author_role varchar(30) NOT NULL REFERENCES user_roles(code),
  comment_type varchar(40) NOT NULL DEFAULT 'GENERAL' REFERENCES comment_types(code),
  content text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_comments_subject ON comments(subject_id);

CREATE TABLE IF NOT EXISTS subject_timeline_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id integer NOT NULL REFERENCES materias(id) ON DELETE CASCADE,
  event_type varchar(80) NOT NULL,
  title varchar(180) NOT NULL,
  description text,
  actor_user_id integer REFERENCES users(id) ON DELETE SET NULL,
  metadata jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_subject_timeline_events_subject ON subject_timeline_events(subject_id);
CREATE INDEX IF NOT EXISTS idx_subject_timeline_events_type ON subject_timeline_events(event_type);
CREATE INDEX IF NOT EXISTS idx_subject_timeline_events_created_at ON subject_timeline_events(created_at);

CREATE TABLE IF NOT EXISTS notification_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id integer REFERENCES materias(id) ON DELETE SET NULL,
  notification_type varchar(60) NOT NULL REFERENCES notification_types(code),
  recipient_email varchar(255) NOT NULL,
  subject_line varchar(255) NOT NULL,
  body_snapshot text NOT NULL,
  status varchar(40) NOT NULL REFERENCES notification_statuses(code),
  error_message text,
  sent_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notification_logs_subject ON notification_logs(subject_id);
CREATE INDEX IF NOT EXISTS idx_notification_logs_status ON notification_logs(status);

CREATE TABLE IF NOT EXISTS audit_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id integer REFERENCES materias(id) ON DELETE SET NULL,
  field_name varchar(120) NOT NULL,
  old_value text,
  new_value text,
  changed_by_user_id integer NOT NULL REFERENCES users(id),
  changed_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_subject ON audit_logs(subject_id);
