CREATE TABLE IF NOT EXISTS subject_transfer_files (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id integer NOT NULL REFERENCES materias(id) ON DELETE CASCADE,
  file_name text NOT NULL,
  file_path text[] NOT NULL DEFAULT '{}',
  mega_url text NOT NULL,
  size_bytes bigint,
  mime_type text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_subject_transfer_files_subject ON subject_transfer_files(subject_id);
