export enum ContentTypeCode {
  VIDEO = "VIDEO",
  PDF = "PDF",
  PODCAST = "PODCAST",
  PRESENTACION = "PRESENTACION",
  ACTIVIDAD_INTERACTIVA = "ACTIVIDAD_INTERACTIVA",
  EVALUACION = "EVALUACION",
  SCORM = "SCORM",
  OTRO = "OTRO",
}
