export enum NotificationType {
  SUBJECT_CREATED = "SUBJECT_CREATED",
  SUBJECT_RETURNED = "SUBJECT_RETURNED",
  SUBJECT_COMPLETED = "SUBJECT_COMPLETED",
  SUBJECT_CORRECTIONS_READY = "SUBJECT_CORRECTIONS_READY",
  SUBJECT_ERROR = "SUBJECT_ERROR",
  SUBJECT_STATUS_UPDATED = "SUBJECT_STATUS_UPDATED",
}
